# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Yash Raj Kapoor'
description: 'Gamer.'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
#dribbble: ''
facebook: 'yash1441'
twitter: 'ygamingplay'
linkedin: 'yash1441'
instagram: 'yash1441'
#pinterest: ''
youtube: 'UCfAF8GAIKweCQHh3qQ1aMrQ'
github-user: 'yash1441'
#gitlab-user: ''
#codepen: ''
steam: 'y-gaming'
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
reddit: 'Y-Gaming'
#medium:  ''
#tumblr: ''
#weibo: ''
#vk: ''
#blog_url: ''
email: 'yash1441@yahoo.com'
#messenger: ''

# Advanced settings
plugins:
  - jekyll-remote-theme
